//
//  LocalDataBase.swift
//  Union
//
//  Created by Камилла Буланова on 09.11.2021.
//

import Foundation

class LocalDataBase {
    static let services = [
        ServiceModel(id: 0,
                     name: "808 Барбершоп",
                     imageName: "barbershopType",
                     type: "Барбершоп",
                     destination: 824.1,
                     address: "Разведчика Ахмерова 5",
                     phoneNumber: "+78005553535",
                     location: [55.797674, 49.179710]),
        ServiceModel(id: 1,
                     name: "Lash - studio",
                     imageName: "hairSalonType",
                     type: "Салон красоты",
                     destination: 2459.3,
                     address: "Пушкина, 13",
                     phoneNumber: "+79088108333",
                     location: [55.788030, 49.122253]),
        ServiceModel(id: 3,
                     name: "Своя",
                     imageName: "shopType",
                     type: "Студия маникюра",
                     destination: 3829.3,
                     address: "Чистопольская, 61б",
                     phoneNumber: "+79179281065",
                     location: [55.819996, 49.132663]),
        ServiceModel(id: 4,
                     name: "YouDaily",
                     imageName: "hairSalonType",
                     type: "Студия красоты",
                     destination: 2405.1,
                     address: "Галимджана Баруди, 4",
                     phoneNumber: "+79872055009",
                     location: [55.818371, 49.065256]),
        ServiceModel(id: 5,
                     name: "Goldi",
                     imageName: "hairSalonType",
                     type: "Салон красоты",
                     destination: 1709.1,
                     address: "Дзержинского, 17",
                     phoneNumber: "+79274954109",
                     location: [55.795565, 49.118109]),
        ServiceModel(id: 6,
                     name: "TOPGUN",
                     imageName: "barbershopType",
                     type: "Барбершоп",
                     destination: 2458.3,
                     address: "Чернышевского, 17",
                     phoneNumber: "+79053747444",
                     location: [55.792314, 49.109929]),
        ServiceModel(id: 7,
                     name: "NEWLINE",
                     imageName: "pharmacyType",
                     type: "Клиника косметологии",
                     destination: 3890.1,
                     address: "Лобачевского, 7",
                     phoneNumber: "+78432363776",
                     location: [55.795414, 49.121500]),
        ServiceModel(id: 8,
                     name: "Скандинавия",
                     imageName: "pharmacyType",
                     type: "Многопрофильная клиника",
                     destination: 2498.1,
                     address: "Профсоюзная, 19/15",
                     phoneNumber: "+78432072334",
                     location: [55.790992, 49.117249]),
        ServiceModel(id: 9,
                     name: "Golden Hands",
                     imageName: "pharmacyType",
                     type: "Студия массажа",
                     destination: 3590.1,
                     address: "Миславского, 9",
                     phoneNumber: "+79520321181",
                     location: [55.796631, 49.112047]),
        ServiceModel(id: 10,
                     name: "Chinaski",
                     imageName: "barbershopType",
                     type: "Барбершоп",
                     destination: 2010.1,
                     address: "Павлюхина, 114",
                     phoneNumber: "+79274470700",
                     location: [55.766845, 49.146770]),
        ServiceModel(id: 11,
                     name: "Brows! & Beauty",
                     imageName: "hairSalonType",
                     type: "Студия красоты",
                     destination: 1430.1,
                     address: "Проспект Победы, 141",
                     phoneNumber: "+79600530091",
                     location: [55.780763, 49.212218])
        ]
}
